import glob
import multiprocessing
import os
import unittest
from datetime import datetime

from sysdiagnose import Sysdiagnose
from sysdiagnose.utils.base import BaseInterface
from sysdiagnose.utils.summary import ExecutionStatus


def _create_case(args):
    """Top-level function for multiprocessing (must be picklable)."""
    archive_file, cases_path = args
    try:
        sd = Sysdiagnose(cases_path=cases_path)
        sd.create_case(archive_file)
        print(f"Created case from {archive_file}")
    except ValueError as ve:
        print(f"Warning: {ve}")


class SysdiagnoseTestCase(unittest.TestCase):
    required_fields_jsonl = ["message", "datetime", "timestamp_desc", "module"]

    @classmethod
    def setUpClass(cls):
        # theoretically better to use tempfile.TemporaryDirectory(), but that would prevent re-use between test runs
        # differently better, and reused over multiple test runs
        # if we'd autogenerated tempdirs we'd also have to figure out a system to pass on the name to the instantiated classes. (singleton?)
        cls.tmp_folder = os.path.join("tests", "tmp")
        os.makedirs(cls.tmp_folder, exist_ok=True)

        cases_path = os.path.join(cls.tmp_folder, "cases")
        cls.sd = Sysdiagnose(cases_path=cases_path)

        # if cases.json does not exist, create cases from testdata,
        # otherwise assume cases are already created and extracted
        if os.path.exists(os.path.join(cases_path, "cases.json")):
            print("Cases already exist, skipping creation")
        else:
            # find all folders such as
            # - testdata/iOSxx/sysdiagnose_YYYY.MM.DD_HH-MM-SS-SSSS_....tar.gz
            # - testdata-private/iOSxx/sysdiagnose_YYYY.MM.DD_HH-MM-SS-SSSS_....tar.gz
            # this allows testing locally with more data, while keeping online tests coherent
            sd_archive_files = glob.glob("tests/testdata*/**/*.tar.gz", recursive=True)

            pool = multiprocessing.Pool()
            try:
                # Register cleanup so workers are killed if the parent is terminated (e.g. IDE stop button)
                import atexit
                import signal

                def _cleanup_pool():
                    pool.terminate()
                    pool.join()

                atexit.register(_cleanup_pool)

                original_sigterm = signal.getsignal(signal.SIGTERM)

                def _sigterm_handler(signum, frame):
                    _cleanup_pool()
                    # Restore original handler and re-raise so the process actually exits
                    signal.signal(signal.SIGTERM, original_sigterm)
                    os.kill(os.getpid(), signal.SIGTERM)

                signal.signal(signal.SIGTERM, _sigterm_handler)

                result = pool.map_async(_create_case, [(f, cases_path) for f in sd_archive_files])
                result.get(timeout=600)
            except KeyboardInterrupt:
                pool.terminate()
                raise
            finally:
                pool.close()
                pool.join()
                atexit.unregister(_cleanup_pool)
                signal.signal(signal.SIGTERM, original_sigterm)

    def setUp(self):
        self.tmp_folder = os.path.join("tests", "tmp")
        cases_path = os.path.join(self.tmp_folder, "cases")
        self.sd = Sysdiagnose(cases_path=cases_path)

    def get_parsers(self):
        """
        List all parsers in the parsers folder.
        We can't use the self.sd.get_parsers() method as that would discard broken parsers.
        """
        results = []
        modules = glob.glob(os.path.join(self.sd.config.parsers_folder, "*.py"))
        for item in modules:
            if item.endswith("__init__.py"):
                continue
            results.append(os.path.splitext(os.path.basename(item))[0])

        results.sort()
        return results

    def get_analysers(self):
        """
        List all analysers in the analysers folder.
        We can't use the self.sd.get_analysers() method as that would discard broken analysers.
        """
        results = []
        modules = glob.glob(os.path.join(self.sd.config.analysers_folder, "*.py"))
        for item in modules:
            if item.endswith("__init__.py"):
                continue
            results.append(os.path.splitext(os.path.basename(item))[0])

        results.sort()
        return results

    def assert_has_required_fields_jsonl(self, entry: dict):
        """
        Check if the entry has all required fields.
        """
        for field in self.required_fields_jsonl:
            self.assertTrue(field in entry, f"Parser result entry did not contain a {field}.")

    def assert_result_summary_consistent(
        self, instance: BaseInterface, result: list | dict | str | None, allow_errors: bool = False
    ) -> None:
        """
        Validates that the ResultSummary is consistent with the actual result produced.

        Args:
            instance: The parser or analyser instance (must have been executed via save_result).
            result: The result returned by get_result().
            allow_errors: If True, do not fail the test when the summary contains errors.
        """
        # Summary file must exist
        self.assertTrue(os.path.isfile(instance.summary_file), "Summary file does not exist")

        summary = instance.get_result_summary()

        # Skipped parsers are not expected to have timing metadata or events
        if summary.status == ExecutionStatus.SKIPPED:
            return

        # Timing metadata must be set
        self.assertIsInstance(summary.start_time, datetime, "start_time must be a datetime")
        self.assertIsNotNone(summary.duration, "duration must be set")
        self.assertGreaterEqual(summary.duration, 0, "duration must be non-negative")

        # Status must be consistent with error/warning counts
        if summary.num_errors > 0:
            self.assertEqual(
                summary.status, ExecutionStatus.ERROR, f"Status should be ERROR when num_errors={summary.num_errors}"
            )
            if not allow_errors:
                self.fail(f"Execution produced {summary.num_errors} error(s).")
        elif summary.num_warnings > 0:
            self.assertEqual(
                summary.status,
                ExecutionStatus.WARNING,
                f"Status should be WARNING when num_warnings={summary.num_warnings}",
            )
        else:
            self.assertEqual(summary.status, ExecutionStatus.OK, "Status should be OK when no errors or warnings")

        # Event count must match actual result length
        if result is not None and instance.format in ("json", "jsonl"):
            if isinstance(result, list):
                self.assertEqual(
                    summary.num_events,
                    len(result),
                    f"num_events ({summary.num_events}) does not match result length ({len(result)})",
                )
            elif isinstance(result, dict):
                # For json format returning a dict, num_events is 1 (the dict itself)
                self.assertGreaterEqual(summary.num_events, 1, "num_events should be >= 1 for dict results")
